export const GET_TOURNAMENTS = 'GET_TOURNAMENTS';
export const LOADING_TOURNAMENTS = 'LOADING_TOURNAMENTS';
export const UPDATE_TOURNAMENT = 'UPDATE_TOURNAMENT';
export const DELETE_TOURNAMENT = 'DELETE_TOURNAMENT';
export const CREATE_TOURNAMENT = 'CREATE_TOURNAMENT';
export const ERROR = 'ERROR';
